source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UILifeCycleClosure_Example', :exclusive => true do
  pod "UILifeCycleClosure", :path => "../"
end

target 'UILifeCycleClosure_Tests', :exclusive => true do
  pod "UILifeCycleClosure", :path => "../"

  
end
