language: objective-c
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods
  - pod install --project-directory=Example

script:
  - pod lib lint --quick
  - set -o pipefail 
  - xcodebuild test -workspace Example/UILifeCycleClosure.xcworkspace -scheme UILifeCycleClosure-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' ONLY_ACTIVE_ARCH=NO | xcpretty -c

notifications:
  email: false
